export enum OrderStatus {
  NEW = 'NEW',
  CHARGED = 'CHARGED',
  PENDING = 'PENDING',
  PENDING_VBV = 'PENDING_VBV',
  AUTHORIZATION_FAILED = 'AUTHORIZATION_FAILED',
  AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
}
