import { generateRandomNumber } from './generateRandomNumber';

export const formatFmsPayload = (payload) => {
  const { name, email, phone } = payload;
  const emId = generateRandomNumber();
  const emCode = generateRandomNumber().toString();

  return {
    user: {
      userName: email,
      userId: generateRandomNumber(),
      emId,
      userStatus: 'Active',
      userRoleId: 1,
      deviceId: null,
      ipAddress: null,
      technicianId: null,
    },
    employee: {
      employeeDetails: {
        initials: null,
        firstName: name,
        lastName: name,
        maidenName: null,
        aliasName: null,
        email,
        emstdId: 78,
        emStatus: 'Active',
        idNumber: null,
        birthDate: null,
        gender: null,
        compName: null,
        dateJoin: null,
        dateLeave: null,
        emPhoto: null,
        lineMngr: null,
        blId: null,
        flId: null,
        rmId: null,
        workType: 'F',
        divId: null,
        depId: null,
        emCode,
        emStdEmStd: null,
        divisionDivCode: null,
        departmentDepCode: null,
        blBlCode: null,
        flFlCode: null,
        rmRmCode: null,
        subDepId: null,
        subDepartmentSubDepCode: null,
      },
      employeeLocation: {
        blId: null,
        flId: null,
        rmId: null,
        workType: 'F',
        blSiteId: null,
        divId: null,
        depId: null,
        subDepId: null,
      },
      employeeContact: {
        phoneWork: phone,
        phonePersonal: phone,
        faxNum: null,
        altContactName: null,
        altContactPhone: null,
      },
      em: {
        emId,
        emCode,
        initials: null,
        firstName: name,
        lastName: name,
        maidenName: null,
        aliasName: null,
        email,
        emStatus: 'Active',
        idNumber: null,
        birthDate: null,
        gender: null,
        phoneHome: phone,
        phoneWork: phone,
        phonePersonal: null,
        faxNum: null,
        altContactName: null,
        altContactPhone: null,
        compName: null,
        dateJoin: null,
        dateLeave: null,
        blId: null,
        flId: null,
        rmId: null,
        lineMngr: null,
        emPhoto: null,
        workType: 'F',
        divId: null,
        depId: null,
        emstdId: null,
        subDepId: null,
      },
    },
    newRecord: 1,
  };
};
